[package]
name = "pseudo-mutex"
version = "0.1.0"
edition = "2021"
keywords = ["mutex","async","realtime"]
authors = ["Geehaich", "CendreQuasar540"]
readme = "readme.md"

[dependencies]
futures = "0.3"
rand = "*"