[package]
name = "magetex"
version = "0.1.0"
edition = "2021"
keywords = ["mutex","async","realtime"]
authors = ["Geehaich", "CendreQuasar540"]
readme = "readme.md"

[dev-dependencies]
futures = "0.3"
rand = "*"